version: '3.8'

services:
  backend:
    build: .
    container_name: backend-container
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/registration-form
    networks:
      - mynetwork

  mongodb:
    image: mongo:6
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=registration-form
    networks:
      - mynetwork

volumes:
  mongodb_data:

networks:
  mynetwork:
